### ISSUE TITLE
improvement for create lead-init-member zarr

### ISSUE THREAD

**Issue by aaronspring** [bradyrx/climpred_CESM1_S2S#1]
see https://github.com/bradyrx/climpred_CESM1_S2S/blob/main/0.01_concatenate_S2S.ipynb

This process can be improved by setting `use_cftime=True` (which reads in the `time` coordinate as `cftime`). Hence the `preprocessing` function could use that coordinate from the first timestep for `init` (probably shift half lead to the exact initialization date),  and then rename `time` to `lead` and make `lead` from integers.

I didnt have that problem, because the data downloaded from IRI comes already concatinated. another interesting question is how the netcdf files are stored on IRI?

@judithberner

**Comment by judithberner** [comment]
Copied from email interaction: 
AS: "From my point of view, we first need to come of with a structure of whether data should be opened via intake-esm, and if so which data goes into which zarr folder. 
https://pangeo-data.github.io/pangeo-cmip6-cloud/ For CMIP6 they just take the data as is on ESGF, but our data is more coherent.
I propose it will be easiest to store one model all vars into one zarr (TBs) or one model one variable (100 GB) into one zarr object. The issue 17 reads similar."
Link to issue 17: 
Issue: https://github.com/pangeo-forge/staged-recipes/issues/17

AS: "From climpred point of view, we loop internally over lead time, so lead time is anyways chunked down by climpred."

**Comment by judithberner** [comment]
Yes, we should strive to use intake-esm. I will get github addressed for NCAR/CISL/intake_easm team.

**Comment by judithberner** [comment]
@ikhomyakov
@abjaye

**Comment by judithberner** [comment]
I will send path to CESM S2S simulations and give write permissions to a large disk. You can always write on your own scratch:
/glade/scratch/aspring

**Comment by aaronspring** [comment]
The main purpose of `intake-esm` for CMIP6 data, other than browsing whats available, is that the `zarr` stores, which are of dimension `lon`, `lat`, `time`, (`level`, `depth`) like the raw model output, are concatinated together by `intake-esm`, e.g. that all member of a given model are concatinated to `lon`, `lat`, `time`, `member_id`. The pangeo CMIP6 cloud data is like has the same contents: Whats `nc` on ESGF or your local replica, is `zarr` on the cloud. no previous concatinations.

However, with our preprocessing from `nc` to `zarr` we have the chance to store all these raw model output `nc` of different `member_id`s, `init`ializations and leads into one large `zarr`. see @rabernat https://github.com/pangeo-forge/staged-recipes/issues/17#issuecomment-766368219

So likely we'll only have one `zarr` per model, because `inits` between models can vary. Probably we can then still use `intake-esm` to `cat.search(member_id=[1,2], variable_id=['t2m', 'precip'])` to specify from these multi-var, multi-dim, multi-init zarr stores or should this rather be done by the user/different program after opening the `zarr`? @andersy005

**Comment by judithberner** [comment]
Aaron - I have a number of communication question. New to github. 
a) should we use Rileys repository and start a new conversation on mine? I forked from his github repo (since he wrote the 
initial scripts - thank you, Riley!!!) , but I can't open an issues on my fork. Maybe I need to do something to "own" it?
b) should we merge the intake_esm and zarrifying S2S discussions or keep them separate.

**Comment by aaronspring** [comment]
Hi Judith, thanks for trying. You will experience that with github you will get very knowledgeable comments. 

a) you own a fork, but for fork you have to activate issues. Go to settings in your fork and scroll down:
![image](https://user-images.githubusercontent.com/12237157/109171785-60e4e700-7782-11eb-84ab-902f2c2b2d7b.png). alternatively you could open your of repository and just copy the code
b) I would not separate intake-esm for S2S and zarrifying S2S, because both decisions influence each other. it is basically on decision.

**Comment by bradyrx** [comment]
@judithberner just wanted to pop in to say happy to see you commenting here! It helps a ton with steering the package toward what is desired by the community. My job is keeping me busy so I can't do any work on the code here, but trying to keep tabs on what is happening still. :)

**Comment by judithberner** [comment]
@bradyrx  So good to "see" you. Happy you are busy with your new job. Yes, Abby and I have worked a lot on adapting your scripts and
hope to eventually upload the ASP S2S tutorial we are developing to climpred. We are also working with Aaron to zarrify CESM and SubX S2S data and have them available in cloud (we have the cloud space!!). We are new to github and all the crowd-sourcing of code, but I am totally convinced (not the least by the two of you) this is the way forward. You and Aaron just have to patient, while we spin up here!!! I will tag on on my fork and then you are welcome to let me know if you want to be taken off (there is probably a way you can do this via git...)
